[project]
name = "ai-swarm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.4.248",
    "langchain>=0.3.18",
    "playwright>=1.50.0",
    "requests>=2.32.3",
]
